### ISSUE TITLE
Update dependency `Newtonsoft.Json`

### ISSUE THREAD

**Issue by o-l-a-v** [OmniSharp/csharp-language-server-protocol#1001]
Please get dependency `Newtonsoft.Json` up to date, both for the security fix found in >= 13.0.1 ( https://github.com/advisories/GHSA-5crp-9r3c-p9vr ), general bugfixes, and for (hopefully) getting the [Azure powershell modules]( https://github.com/Azure/azure-powershell) to work with the [Visual Studio Code PowerShell extension]( https://github.com/PowerShell/vscode-powershell) + Windows PowerShell 5.1, where `OmniSharp/csharp-language-server-protocol` is a component in [PowerShellEditorServices](https://github.com/PowerShell/PowerShellEditorServices).

Seems the renovate bot made a PR to update `Newtonsoft.Json`, but some check failed (?) and it hasn't been merged:

* https://github.com/OmniSharp/csharp-language-server-protocol/pull/839

Related issues:

* Azure PowerShell: https://github.com/Azure/azure-powershell/issues/21647
* PowerShellEditorServices: https://github.com/PowerShell/PowerShellEditorServices/issues/2030

---

Edit: I see now that the security fix is already mitigated by setting max depth for JSON serialization. Still, would be nice to get `Netwonsoft.Json` up to date for the two other mentioned reasons.

**Comment by JoeRobich** [comment]
Closing as #839 has merged.
