### ISSUE TITLE
Missing FoldingRange implementation

### ISSUE THREAD

**Issue by NickAcPT** [OmniSharp/csharp-language-server-protocol#101]
I started implementing it in pr #100, but I'm in need of some guidance.

**Comment by NickAcPT** [comment]
Closing this issue since it has become stale and the pull request has been merged since then.

**Comment by fgreinacher** [comment]
@NickAcPT Did you ever try whether this works with commonly used clients? I tried with Monaco/Theia but it seems like the client capability is not detected correctly.

**Comment by NickAcPT** [comment]
@fgreinacher, first of all, I apologise the big delay of this reply.
In PR #100, I had just barely implemented FoldingRange, which was later merged and worked upon by other contributors. It was just a starting point, so I'm not sure I can provide any help with this one and sorry for any inconveniences I may have caused.

**Comment by fgreinacher** [comment]
No worries, I just saw some issues there and wasn't sure where the problem was. Now I know 🤣 Fix is in #143
