### ISSUE TITLE
MinimumLogLevel is not respected in options configuration

### ISSUE THREAD

**Issue by NTaylorMullen** [OmniSharp/csharp-language-server-protocol#106]
https://github.com/OmniSharp/csharp-language-server-protocol/blob/4050dad05963ac5d7df3579345bde9edd25971fb/src/Server/LanguageServer.cs#L171 overrides all log level settings done in the "From" clause.

**Comment by StephenWeatherford** [comment]
This didn't fix it - the option is never inspected when creating the language server.

        public static async Task<ILanguageServer> From(LanguageServerOptions options, CancellationToken token)
        {
            var server = new LanguageServer(
                options.Input,
                options.Output,
                options.Reciever,
                options.RequestProcessIdentifier,
                options.LoggerFactory,
                options.Serializer,
                options.Services,
                options.HandlerTypes.Select(x => x.Assembly)
                    .Distinct().Concat(options.HandlerAssemblies),
                options.InitializeDelegates,
                options.InitializedDelegates
            );

            if (options.AddDefaultLoggingProvider)
                options.LoggerFactory.AddProvider(new LanguageServerLoggerProvider(server));

            await server.Initialize(token);

            return server;
        }

**Comment by david-driscoll** [comment]
A lot of the logging infrastructure has been rebuilt, if this is still an issue let me know and I can reopen it.

**Comment by StephenWeatherford** [comment]
Is there a place to go to find out how to use the new infrastructure?
