### ISSUE TITLE
MarkdownString vs MarkedString

### ISSUE THREAD

**Issue by tintoy** [OmniSharp/csharp-language-server-protocol#107]
Looks like `MarkedString` is becoming `MarkdownString` (with an additional `isTrusted` property):

https://github.com/Microsoft/vscode/issues/33577

@david-driscoll - what's your preference here; would you like to mirror their API change (`MarkedString -> MarkdownString`), or just add the property to `MarkedString`?

**Comment by tintoy** [comment]
It also looks like hyperlinks to local file-system paths are not rendered correctly (in hover tooltips, at least) without `isTrusted: true`, BTW.

**Comment by david-driscoll** [comment]
@tintoy lets do it, I'm okay with the breaking change (we'll just minor bump things)

**Comment by david-driscoll** [comment]
Lets actually just make a new `MarkdownString` class that inherits from `MarkedString`, but add the new property to `MarkedString`.  That way we can be backwards compatible, but support the new API going forward.

**Comment by tintoy** [comment]
Ok - will have a go at this tomorrow morning then :)

**Comment by david-driscoll** [comment]
I think is superseeded by `MarkupContent`
