### ISSUE TITLE
FileRename record implementation is incorrect

### ISSUE THREAD

**Issue by hozuki** [OmniSharp/csharp-language-server-protocol#1078]
In [specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#fileRename):

```typescript
export interface FileRename {
    oldUri: string;
    newUri: string;
}
```

In [protocol implementation](https://github.com/OmniSharp/csharp-language-server-protocol/blob/master/src/Protocol/Features/FileOperationsFeature.cs#L111):

```csharp
public abstract record FileOperationItem
{
    public Uri Uri { get; init; } = null!;
}

public partial record FileRename : FileOperationItem;
```

When using `DidRenameFileParams`/`WillRenameFileParams` (handling `workspace/didRenameFiles`/`workspace/willRenameFiles`), items in `request.Files` only include one URI. I haven't tested the requests but I suppose the param objects cannot be deserialized as expected.
(Packages like `vscode-languagesclient` implement this correctly.)

---

By the way, shouldn't these classes be named as _DidRenameFile**s**Params_/_WillRenameFile**s**Params_ (plural form; the same also applies to corresponding handler classes and interfaces)?

**Comment by zreedy** [comment]
Hello, it appears that this fix is not in a release yet. Any idea when this will make it into a Release?
In the meantime, is there any possible work around? I'm not sure if I can override the default deserializer for this message.
