### ISSUE TITLE
Add license to NuGet package

### ISSUE THREAD

**Issue by danroth27** [OmniSharp/csharp-language-server-protocol#108]
Looks like the OmniSharp.Extensions.LanguageProtocol package doesn't have any license info.

**Comment by danroth27** [comment]
License also missing from the LanguageProtocol and JsonRpc packages.

**Comment by david-driscoll** [comment]
@danroth27 I can add that.

**Comment by danroth27** [comment]
@david-driscoll Thanks! What license do you plan to use for the packages? Will it be the same MIT license used for the source code?

**Comment by david-driscoll** [comment]
@danroth27 yeah, I'm going to do that right now.
