### ISSUE TITLE
Missing params key for empty notifications

### ISSUE THREAD

**Issue by Yarith** [OmniSharp/csharp-language-server-protocol#110]
Hello, 
i found this while i was playing around with the language server protocol and hie today.

The ```LanguageClient``` sends empty notifications without the ```params``` key.  The vscode-languageclient sends in this case the null value ```{}```: [main.ts#L940](https://github.com/Microsoft/vscode-languageserver-node/blob/3c48412e5f019ddc61a43cc2e0ed3bbcfd08696c/jsonrpc/src/main.ts#L940)

This causes an error in the Haskell language server from the Haskell IDE Engine (hie). They are getting reported by a ```window/logMessage```:
```json
{
  "type": 1,
  "message": "haskell-lsp:parse error. Object (fromList [(\"jsonrpc\",String \"2.0\"),(\"method\",String \"initialized\")]) \"When parsing the record NotificationMessage of type Language.Haskell.LSP.Types.Message.NotificationMessage the key params was not present.\" `stack update` and install new haskell-lsp. Or check information on https://marketplace.visualstudio.com/items?itemName=xxxxxxxxxxxxxxx"
}
```

The error disappears if i set under [LspConnection.cs#L318](https://github.com/OmniSharp/csharp-language-server-protocol/blob/38c2b44f7f3ce44873b66d54ecf0b2b86806e832/src/Client/Protocol/LspConnection.cs#L318) the property ```Params``` to ```JValue.CreateNull()```:
```csharp
new ClientMessage
{
    // No Id means it's a notification.
    Method = method,
    Params = JValue.CreateNull()
}
```

**Comment by david-driscoll** [comment]
cc @tintoy

**Comment by lordmilko** [comment]
I ran into the exact same thing, also with the Haskell IDE Engine

According to the [LSP Specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialized), the `initialized` notification is defined as follows

> method: ‘initialized’
> params: InitializedParams defined as follows:
> ```
> interface InitializedParams {
> }
> ```

Based on this information, this project appears to be in clear violation of the spec

**Comment by lordmilko** [comment]
@david-driscoll,

Has this issue now been resolved?
