### ISSUE TITLE
Can we expose the IServiceProvider used by the language server?

### ISSUE THREAD

**Issue by tintoy** [OmniSharp/csharp-language-server-protocol#111]
I need to get hold of a singleton handler instance used by the server because this raises events that other components need to subscribe to. Or I'm open to other approaches if you can think of any :)

Basically, when the configured log level changes, I need to dynamically adjust the server's log level.

**Comment by mholo65** [comment]
@tintoy I believe this is now fixed. Close?

**Comment by tintoy** [comment]
Yep, thanks!
