### ISSUE TITLE
I want to run this language server standalone. Can please someone provide me the documentation?. I can't find the steps anywhere. 

### ISSUE THREAD

**Issue by ManishAgrawal1410** [OmniSharp/csharp-language-server-protocol#113]

**Comment by tintoy** [comment]
Hi - do you mean consuming an existing language server as a client?

**Comment by Mattuple** [comment]
Hi, I think I have the same question.

I would like to run the server as an executable and connect with stdin/out. I see there is a Sampleserver exe.

I've managed to connect to this using Monaco and the language client (https://github.com/TypeFox/monaco-languageclient). The server connects/initialises and shutdown quit works but no other functionality is provided.

Do I have to write my own handlers for the sample server? Or are they provided somewhere in this csharp LSP?

I need hover, function signature and auto-complete.

Thanks for your time, M.

**Comment by tintoy** [comment]
Hi just to clarify, which server do you want to run?

**Comment by tintoy** [comment]
Yep, this is a library for creating language servers or using existing language servers as a client. There are a couple of servers out there such as https://github.com/tintoy/msbuild-project-tools-server, but note that it's built against an earlier version of the server (and is quite a complex language servic) so may not be the best example. As for using the client, I'll see if I can dig up some sample code.

**Comment by Mattuple** [comment]
Thanks, I was trying to find code that doesn’t exist!

There is the sample server project included here and this looks like the basis of what I need. Standalone exe, std in/out and a few handlers in the TextDocumentHandler class for DidChangeTextDocumentParams etc.

So I’d need to register handlers for the features I need, like the HoverParams class? 
If you have some source for this then that would be excellent.

**Comment by tintoy** [comment]
Here's an example for the client:

https://gist.github.com/tintoy/a2ec9424d17fe9ef17db0621479a7b43

As for the server, I believe the sample server already shows how to register your handlers:

https://github.com/OmniSharp/csharp-language-server-protocol/blob/38c2b44f7f3ce44873b66d54ecf0b2b86806e832/sample/SampleServer/Program.cs#L31

(you'll need to create a class that implements `IHoverHandler` and register it to support hover content)

**Comment by tintoy** [comment]
(sorry, on my phone so typing is a bit of a pain)

**Comment by chenzhegodspeed** [comment]
The reason why I want to do my work with Omnisharp LS is that I find Omni is the maintainer of C# in the Implementations list of LSP. I think Omni's parser for C# will be great because it is  "official" team.

**Comment by tintoy** [comment]
You can download the latest version of the OmniSharp server here:

https://github.com/OmniSharp/omnisharp-roslyn/releases

Just be aware that OmniSharp has a somewhat complex implementation in terms of LSP (there are a fair number of custom endpoints / messages) and so it may take you a while to get this working to your satisfaction :)

BTW, OmniSharp itself [uses Microsoft Roslyn](https://github.com/OmniSharp/omnisharp-roslyn#introduction) to parse and interpret your projects and source files so either approach can give you what you want.

**Comment by tintoy** [comment]
Here's the LSP implementation used by OmniSharp:

https://github.com/OmniSharp/omnisharp-roslyn/tree/master/src/OmniSharp.LanguageServerProtocol
