### ISSUE TITLE
IWorkspaceSymbolsHandler cannot be registered

### ISSUE THREAD

**Issue by drsoran** [OmniSharp/csharp-language-server-protocol#114]
I've implemented the IWorkspaceSymbolsHandler interface for my handler. But up to now I was not able to register it. I tried with VS Code 1.29.1.

I checked #80 that is similar but I think not the same cause.

What I observed:
When start the language server by LanguageServer.From(...), the ClientCapabilityProvider is asked for HasStaticHandler(workspaceCapabilities.Symbol). This returns false because VSCode states it supports dynamic registration.

Later I add my handler implementations by AddHandlers(params IJsonRpcHandler[] handlers). This filters out my IWorkspaceSymbolsHandler implementation because IWorkspaceSymbolsHandler does not derives from IRegistration<>.

Currently I see no way how to register this handler. Btw. I have the same problem with IWorkspaceFoldersHandler.

Perhaps I do something wrong?

**Comment by david-driscoll** [comment]
It's likely that you're not doing something wrong, and that we have to fix that part.

**Comment by david-driscoll** [comment]
I think this has been fixed in the latest version, or in the next version.

**Comment by drsoran** [comment]
Works perfect. Sorry for the late answer.
