### ISSUE TITLE
build.sh stuck for long at test execution

### ISSUE THREAD

**Issue by Aayush04** [OmniSharp/csharp-language-server-protocol#115]
I am unable to build the csharp-language-server-protocol. While running build.sh, it is getting stuck at test execution for an indefinite time.

<img width="655" alt="screen shot 2018-12-17 at 3 35 10 pm" src="https://user-images.githubusercontent.com/4752354/50080127-698c1b00-0211-11e9-9304-0669b0e61d85.png">

and nothing happens after this. Any idea how to run build.sh?

**Comment by david-driscoll** [comment]
I know I've seen some of the tests in the client that just sit around waiting, but I'm not yet sure what the true cause is of that unfortunately.

**Comment by david-driscoll** [comment]
Mac builds have been fixed and are working with both azure devops and github actions at the moment.
