### ISSUE TITLE
Impossible to have multiple IDidChangeTextDocumentHandlers

### ISSUE THREAD

**Issue by NickAcPT** [OmniSharp/csharp-language-server-protocol#120]
I've tried using multiple handlers that extend IDidChangeTextDocumentHandler and only the first one is working and being registered.
Registering them both with `LanguageServerOptions.WithHandler`.

The code:
```csharp
var server = await LanguageServer.From(options =>
    options
        .WithInput(Console.OpenStandardInput())
        .WithOutput(Console.OpenStandardOutput())
        .WithLoggerFactory(new LoggerFactory())
        .AddDefaultLoggingProvider()
        .WithMinimumLogLevel(LogLevel.Trace)
        .WithHandler<TextDocumentHandler>() //My first handler; Using the default one from the sample
        .WithHandler<InspectionDocumentHandler>() //My second handler that extends IDidChangeTextDocumentHandlers
);
```

I need to have multiple ones because on `TextDocumentHandler` I have it to do a full sync of the text, but on `InspectionDocumentHandler` I need it to have it do incremental sync.

**Comment by NickAcPT** [comment]
@david-driscoll sorry for the ping.
Meanwhile, is there a plausible workaround for the time being for this issue?

**Comment by david-driscoll** [comment]
@NickAcPT sorry for the delay!  I'm going to see if this has been solved or what is the cause of the issue.

**Comment by NickAcPT** [comment]
Thank you so much and no worries! Take your time. Anything I can help with?

**Comment by david-driscoll** [comment]
Do they handlers target the same document selector?

**Comment by NickAcPT** [comment]
Yeah. Is that what was causing the problem?

**Comment by david-driscoll** [comment]
I believe so.  the `HandlerDescriptor`s are stored in a `HashSet` with a key that combines the type, method, and the document selector (if it applies to the handler).

For your use case what do you want to happen with the additional handler?  Do you want it to trigger for both?

The assumption I made originally (which may be a bad one) was that we'd have one unique handler for those combinations, but that is really an assumption around requests, you can only have one request return a response, but notifications are different however.

Now that I understand the issue I think I can come up with something where notifications will work slightly differently than requests.

**Comment by NickAcPT** [comment]
Well, my main idea was to have two handlers, where each one had the same document selector but a different `TextDocumentSyncKind`. An example of this could be having one document handler to handle the file changes (with `TextDocumentSyncKind.Full`) and another where it could run code diagnostics just on the changed regions (with `TextDocumentSyncKind.Incremental`).

In my head, I wanted it separate because there was no method to correctly handle `TextDocumentSyncKind.Incremental` and I didn't want to go through the trouble of doing that to handle edit synchronization between the client and the server. 😄

**Comment by david-driscoll** [comment]
ahhh.  I have no idea how common clients like vscode would react to that.  I assume if we register the same document selector multiple times, as long as they support dynamic registration it should work.  

The problem I can't get past at the moment is how to properly route the notifications, because we see is the document uri, which means you'll get some requests as full text and some as incremental to _both_ handlers.

**Comment by NickAcPT** [comment]
I see. In that case, what is the best thing to do? Close this issue and just use one handler? I feel there's no need to over complicate things just because of this one request. 😄

**Comment by david-driscoll** [comment]
Yeah, I think this one would be really hard to handle unfortunately!  Sorry!
