### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by raizam** [OmniSharp/csharp-language-server-protocol#125]
Hi, I would really appreciate some help, I've set a vscode language extension client, and a c# server.
Now I'd like the vscode extension to consume the server instance launched from visual studio, in order to debug. How does it work?
Thanks

**Comment by david-driscoll** [comment]
There is sadly no nice way, that I'm aware of that to do this... you could potentially connect to your language server via a socket or a named pipe, in such a way that you can connect to the server after it's started.

I generally have a `--debug` argument that halts my server process until the debugger is attached, then attach through vscode / visual studio directly.

**Comment by raizam** [comment]
I was using `Debugger.Launch();` in the server main function, it wasn't practical at all.
Now I'm using the Reattach extension and things got more pleasant.
https://marketplace.visualstudio.com/items?itemName=ErlandR.ReAttach
