### ISSUE TITLE
FilePaths with foreign characters can't be used for LSP events to the server

### ISSUE THREAD

**Issue by NTaylorMullen** [OmniSharp/csharp-language-server-protocol#131]
See https://github.com/aspnet/Razor.VSCode/issues/252.

Dan mentioned it might be due to:

```
Is the issue here possibly that we need to enable IRI support in System.Uri?:

https://docs.microsoft.com/en-us/dotnet/framework/network-programming/international-resource-identifier-support-in-system-uri

Daniel Roth
```

**Comment by david-driscoll** [comment]
@NTaylorMullen I tried adding a test and things appear to work on my end, I wonder if vscode is somehow mangling the uri?

See: #130

**Comment by NTaylorMullen** [comment]
> I wonder if vscode is somehow mangling the uri?

Hmmm, maybe? That being said I'd imagine there would be a whole lot more issues if they weren't following the spec for the LSP URI.

**Comment by NTaylorMullen** [comment]
Maybe it's the cross-plat URI impl? One user in VSCode's path was: `/home/tiago/Área de Trabalho/projeto/ONE/SOURCE/Site/Views/Cadastro/Parametro/Usuario/Index.cshtml`

**Comment by NTaylorMullen** [comment]
This looked to be due to the version of .NET Core I was using. Upgrading to netcoreapp2.2 in my app fixed the problem.
