### ISSUE TITLE
[LSP] textDocument/documentColor RGB values should be floating point

### ISSUE THREAD

**Issue by jeremybeier** [OmniSharp/csharp-language-server-protocol#134]
## Issue
The RGB values should be of type double, not int.
> csharp-language-server-protocol/src/Protocol/Models/Color.cs 

### According to the [lsp inspector](https://microsoft.github.io/language-server-protocol/inspector/):
![image](https://user-images.githubusercontent.com/22215375/55558181-cdb4eb00-56eb-11e9-81b2-b329a3468409.png)

**Comment by mholo65** [comment]
Fixed in #135
