### ISSUE TITLE
completion results are not coming proper untill didChange message sent

### ISSUE THREAD

**Issue by Aayush04** [OmniSharp/csharp-language-server-protocol#138]
I am using this csharp language server with Monaco language client. Found that csharp language server is not returning proper completion result. It seems like the language server does not aware that I am hitting the control space inside a class.
It is giving results same as when hitting outside the class scope. But it started working well when I send a didChange message to the language server. By making the changes in the whole file. (i simply copy and paste the same content)
Please find attached screenshot for better understanding: -

**When the completion not working properly**
<img width="823" alt="Screen Shot 2019-05-13 at 4 18 17 PM" src="https://user-images.githubusercontent.com/4752354/57616691-661c7600-759c-11e9-95c5-b57ac4d0c366.png">

Socket Messages:
<img width="1383" alt="Screen Shot 2019-05-13 at 4 18 30 PM" src="https://user-images.githubusercontent.com/4752354/57616707-72083800-759c-11e9-9403-2fe733398215.png">

Then I clicked on the` Reset Same Value` Button, which simply sets the same value to the editor and then languageClients sends a didChange message on socket. After this completion started working properly.
**Please note:** on making any other change in value does not solves the problem. It seems like if the changed text has the whole class in it then the completions started working, So, I am setting the whole text again.

**Completion working properly**
<img width="829" alt="Screen Shot 2019-05-13 at 4 18 49 PM" src="https://user-images.githubusercontent.com/4752354/57616794-bc89b480-759c-11e9-9442-5d08800be502.png">

**Socket Messages:**
<img width="1402" alt="Screen Shot 2019-05-13 at 4 19 15 PM" src="https://user-images.githubusercontent.com/4752354/57616805-c3182c00-759c-11e9-87ff-e3049bce860d.png">

Please let me know what is happening wrong here? Why language server needs didChange event explicitly. 
Note: I am using csharp language server as a dependency in [omnisharp-roslyn ](https://github.com/OmniSharp/omnisharp-roslyn) implementation.

**Comment by mholo65** [comment]
@Aayush04 is the server you are implementing open source, if yes, can you point me to the source? Are you experiencing same behavior if using VS Code instead of Monaco?

**Comment by Aayush04** [comment]
@mholo65 No, it is not an open-source.  But I am using the same what is mentioned in the documentation of [MonacoLanguageClient](https://github.com/TypeFox/monaco-languageclient/blob/master/example/src/client.ts).

Yes, I tried to check the same thing on the vscode. With the omnisharp's extension only. But it is working fine there.

**Comment by david-driscoll** [comment]
It's hard to identify where the issue might be.  From the sounds of it the server isn't loading the content of the file until it's forced to change.  That isn't really something that is on the library side of the problem, all we're doing is wrapping up LSP and making it easier to consume.

One thing to make sure is that the server is using the content of the `didOpen` event and populating the buffer (or whatever construct it is using), that is most likely the problem.

**Comment by david-driscoll** [comment]
I think this is a user side issue, closing for now, let us know if you still are having problems.
