### ISSUE TITLE
Allow handlers to return a custom ErrorResponse

### ISSUE THREAD

**Issue by rjmholt** [OmniSharp/csharp-language-server-protocol#144]
I might have some misconceptions about how this LSP implementation works, so feel free to correct me!

The LSP spec says [responses may be error responses](https://microsoft.github.io/language-server-protocol/specification#response-message). Looking at the `IJsonRpcRequestHandler<TParams, TResponse>` interface, it looks like the handler is constrained by its generic instantiation as to the response it can return. (I know there are some implicit assumptions there, so I might have misunderstood).

I have a handler that can fail and its current behaviour is to send an error response message in that circumstance. Is there a way that would be possible with the OmniSharp LSP server?

I found an instance of this in the RequestRouter here:
https://github.com/OmniSharp/csharp-language-server-protocol/blob/c919309e4f7f28cd99a6540be8ed51ab7684abd5/src/JsonRpc/RequestRouter.cs#L57-L99

But I'm guessing this isn't available from a higher layer (perhaps my intended behaviour is a layering violation?).

So my questions are:
- Is there a way for a handler to return an ErrorResponse? (Should a handler return an ErrorResponse?)
- If not, is the "correct" behaviour of a handler given erroneous input to just throw (which is then translated into an error response at the router layer)?

**Comment by david-driscoll** [comment]
@rjmholt I built things around the idea that if you needed to return an error you would just throw an exception and then the library would just manage and return the error for you in the correct format.

There is a change to the request router coming that should improve what you are seeing a little bit.  I'm basically merging the LSP and JsonRpc request routers (they are current different).

I'm going to add an exception you could throw `RpcErrorException`  that will let you return a specific code back to the client.

**Comment by rjmholt** [comment]
> @rjmholt I built things around the idea that if you needed to return an error you would just throw an exception and then the library would just manage and return the error for you in the correct format.

Ah, yes after I asked I realised that's what I should be doing, which feels like a nice way of doing things to me :)

> I'm going to add an exception you could throw RpcErrorException that will let you return a specific code back to the client.

Given the above, that's exactly what I would have asked for

**Comment by rjmholt** [comment]
Reopened to track adding this

**Comment by TylerLeonhardt** [comment]
This is actually a thing already. My bad
