### ISSUE TITLE
Debug Adapter Protocol lib

### ISSUE THREAD

**Issue by TylerLeonhardt** [OmniSharp/csharp-language-server-protocol#145]
Hi all 👋

The PowerShell language server will start making the transition to using the csharp-language-server-protocol project for the LSP message handling!

If you have any concerns about this, please let me know but I was wondering if there was a DAP implementation in C# that’s recommended to go along side this project.

Any thoughts?

* [x] protocol types
* [x] extensible `launch` and `attach`
* [x] `DebugServer` type
* [x] `DebugClient` type

**Comment by david-driscoll** [comment]
I have not sat down to start work on a lib for the debug stuff, but it's something we could probably do fairly easily, I think they're both JsonRpc based iirc.

**Comment by TylerLeonhardt** [comment]
Yeah, the [DAP is a bit strange…](https://microsoft.github.io/debug-adapter-protocol/overview) not pure jRPC I think… but should be doable.

**Comment by TylerLeonhardt** [comment]
@david-driscoll If you folks can do the underlying work of giving me the ability to mark a message as “LSP or DAP” I can help csharp-language-server-protocol by creating most/all of the message interfaces & param types.

**Comment by TylerLeonhardt** [comment]
cc @mholo65

**Comment by TylerLeonhardt** [comment]
This is technically done... but it would be nice to have a formal `DebugServer` type similar to `LanguageServer`. It doesn't have to be too fancy, but ideally it would handle stuff like [`initialize`](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Initialize) [`cancel`](https://microsoft.github.io/debug-adapter-protocol/specification#Base_Protocol_Cancel).

**Comment by TylerLeonhardt** [comment]
Additionally, a `DebugClient` offering similar things to `LanguageClient` would be awesome.

cc @tintoy who has done great work on the `LanguageClient`

**Comment by david-driscoll** [comment]
Getting a DebugServer is next on my list... we can basically just steal the code you worked on it get things working! 👍

**Comment by TylerLeonhardt** [comment]
More or less. There's a ton of PSES specific code in there but it could be used as an example along with `LanguageServer`

**Comment by TylerLeonhardt** [comment]
Oh I forgot to mention... For the `launch` and `attach` request, I had to make own handlers because we add more properties to the `launch.json`.

Ex. Attach to process:
```json
        {
                name: "PowerShell: Attach to PowerShell Host Process",
                type: "PowerShell",
                request: "attach",
                runspaceId: 1,
            }
```
Note the `runspaceId`.

So one other thing this needs is extensible launch/attach requests.

**Comment by TylerLeonhardt** [comment]
@tintoy I remember in Slack you said you had a `DebugClient` ready for me to try. Is that true?

**Comment by tintoy** [comment]
On my own branch yeah - it should be enough to get you started at least :)

https://github.com/tintoy/csharp-language-server-protocol/tree/feature/dap/client?files=1

**Comment by david-driscoll** [comment]
I think we have these now!
