### ISSUE TITLE
How do I get the logger/service connection to my Handler?

### ISSUE THREAD

**Issue by TylerLeonhardt** [OmniSharp/csharp-language-server-protocol#146]
[Here’s my handler code](https://github.com/rjmholt/PowerShellEditorServices/blob/2a53c9c783dbf382cf2aa08d07c049b660c68ec1/src/PowerShellEditorServices.Engine/Services/Workspace/Handlers/WorkspaceSymbolsHandler.cs)

It doesn’t do anything. Just sends an empty list back… but I want to grab the logger that I registered with the service collection [here](https://github.com/rjmholt/PowerShellEditorServices/blob/2a53c9c783dbf382cf2aa08d07c049b660c68ec1/src/PowerShellEditorServices.Engine/Hosting/EditorServicesHost.cs#L137):

```csharp
_serviceCollection.AddLogging(loggingBuilder => loggingBuilder.AddSerilog(dispose: true));
```

Also while I have you, is this the correct way of registering handlers:

```csharp
options.WithHandler<WorkspaceSymbolsHandler>();
```
That’s from [here](https://github.com/rjmholt/PowerShellEditorServices/blob/2a53c9c783dbf382cf2aa08d07c049b660c68ec1/src/PowerShellEditorServices.Engine/LanguageServer/OmnisharpLanguageServer.cs#L71).

**Comment by david-driscoll** [comment]
`ILogger<T>` should resolve a logger.
see: 
https://github.com/aspnet/Extensions/blob/f162f1006bf8954f0102af8ff98c04077cf21b04/src/Logging/Logging/src/LoggingServiceCollectionExtensions.cs#L41-L42

And yes that should register handlers correctly.

Let me know if you need any more help with this!
