### ISSUE TITLE
Good news - it's working with vscode

### ISSUE THREAD

**Issue by Lercher** [OmniSharp/csharp-language-server-protocol#16]
Not really an issue, but worth mentioning IMHO: How cool is that? Using @david-driscoll's 🥇 .Net protocol libraries, I've now implemented with little effort, several behaviors that I feel are central for a language server for DSLs, such as

* Background parsing with diagnostics notification
* Go to definition for symbols
* Find all references of symbols
* Hover, i.e. "tooltips on steroids"
* Rename symbol [edit]
* Completion [edit]
* But not yet CodeLens. It's weird (to my current understanding) at the protocol level because it needs commands that aren't routed to the language server by default. [edit]
 
for vscode. It's working efficiently on two different machines, and until now, I didn't find issues with localized sources, i.e. non ASCII files. Such as garbled umlaut characters or positions that are off by some characters, you name it.

For details and future enhancements, please see https://github.com/Lercher/csharp-language-server-protocol/blob/coco-r/sample/SampleServer/Readme.md#evaluating-implemented-language-server-features

Martin

edit: see [edit]

**Comment by mickaelistria** [comment]
Have you compared it with https://github.com/OmniSharp/omnisharp-node-client ? Do you think the current start of csharp-language-server-protocol is already worth replacing what's shipped in https://github.com/OmniSharp/omnisharp-node-client ?
cc @david-driscoll

**Comment by Lercher** [comment]
No, because it does not apply: I'm not interested in building yet another C# language server. 

My interest is to build language servers for arbitrary grammars that are parse-able by my extended variant of the Coco/R compiler compiler and currently this tool was not ported to JavaScript (according to my knowledge).  But it exists for .Net, so at least I need a .Net protocol implementation and this one does it's job well.

**Comment by david-driscoll** [comment]
@mickaelistria this is just a library to create a server that is compatible with LSP, it's not a C# implementation of the server.  I will be adding LSP support to https://github.com/OmniSharp/omnisharp-roslyn in a week or two (time permitting at the moment).  At which point the way to get it running would be simply setting an `--lsp` flag.

**Comment by sshumakov** [comment]
Hi @david-driscoll, do you plan to implement C# server? I took a quick overview of the code and it seems that library expects to be used by the server.

**Comment by hadi77ir** [comment]
@sshumakov It is not a library for "implementing C# language server", it is for "implementing ANY language server", for example a "VB.NET Language Server" or a "Boo Language Server".

**Comment by david-driscoll** [comment]
I do plan on implementing this in Omnisharp... I just won't have time for the rest of this month, but I'll be taking time in August to do some work.

**Comment by sshumakov** [comment]
Good news @david-driscoll. I see that based on sample, the usage is as follows:

`                    var server = new LanguageServer(reader, writer);
                    server.AddHandler(new TextDocumentHandler(server));
                    await server.Initialize();`

Do I understand it correctly that library expects 1 server per 1 client, not 1 client per multiple servers?

**Comment by sshumakov** [comment]
@hadi77ir , I didn't state that it is for C# only, I was asking specifically about C# server implementation.

**Comment by sshumakov** [comment]
@david-driscoll, I would like to also mention that integration I was talking about was with monaco editor (copy of VS Code in browser) and language server. I would like to setup this editor to talk with server to provide basic stuff like code completion etc.

**Comment by kyurdakok** [comment]
> I do plan on implementing this in Omnisharp... I just won't have time for the rest of this month, but I'll be taking time in August to do some work.

any updates on that?

**Comment by david-driscoll** [comment]
@sshumakov interesting I hadn't thought about multiple possible input streams yet (collaboration style) it's something we could add in however.

@kyurdakok unfortunately no, been swamped with work, and evening work.  I am going to try and make time Saturday to start working on the implementation in OmniSharp-roslyn, so that others could perhaps come in and help with plugging all the bits in.

**Comment by david-driscoll** [comment]
Closing for now.

Work has started in omnisharp https://github.com/OmniSharp/omnisharp-roslyn/pull/969
