### ISSUE TITLE
JsonRpcException at workspace/applyEdit with CreateFile

### ISSUE THREAD

**Issue by stfuzz** [OmniSharp/csharp-language-server-protocol#165]
**The attached code fails with the following exception. Please ask if something is not clear.**

{Request workspace/applyEdit failed with message: Cannot read property 'version' of undefined}

OmniSharp.Extensions.JsonRpc.Server.JsonRpcException
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.ResponseRouter.<SendRequest>d__8\`2.MoveNext() in /_/src/JsonRpc/ResponseRouter.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter\`1.GetResult()
   at ***LSP.Server.Handlers.CustomHandler.<Handle>d__6.MoveNext() in C:\***LSP\Server\Handlers\CustomHandler.cs:line 109

            var uri = new Uri("file:///" + filePath);
            var changes = new Container<WorkspaceEditDocumentChange>(
                new WorkspaceEditDocumentChange(new CreateFile() { Uri = uri.ToString(), Options = new CreateFileOptions() { IgnoreIfExists = true} }),
                new WorkspaceEditDocumentChange(
                    new TextDocumentEdit()
                    {
                        TextDocument = new VersionedTextDocumentIdentifier()
                        {
                            Uri = uri
                        },
                        Edits = new Container<TextEdit>(
                            new TextEdit()
                            {
                                NewText = content
                            }
                        )
                    }
                )
            );

            return ApplyEditExtensions.ApplyEdit(workspace, new ApplyWorkspaceEditParams()
            {
                Edit = new WorkspaceEdit()
                {
                    DocumentChanges = changes, // using Changes instead of DocumentChanges works fine, but you cannot create a new file
                }
            });

>     OmniSharp.Extensions.JsonRpc (0.13.1)
>     OmniSharp.Extensions.LanguageProtocol (0.13.1)
>       OmniSharp.Extensions.JsonRpc (>= 0.13.1)
>     OmniSharp.Extensions.LanguageServer (0.13.1)
>       OmniSharp.Extensions.JsonRpc (>= 0.13.1)
>       OmniSharp.Extensions.LanguageProtocol (>= 0.13.1)
>

**Comment by stfuzz** [comment]
Update: if I comment out the line involving CreateFile() there is no such exception

**Comment by stfuzz** [comment]
it also makes no difference wrapping new CreateFile() and new TextDocumenEdit() in each WorkspaceEditDocumentChange or not

**Comment by david-driscoll** [comment]
You need to include the document version in  the text document edit  see: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocumentEdit

**Comment by stfuzz** [comment]
Oh, thank you for your hint!
