### ISSUE TITLE
Supported Client Features

### ISSUE THREAD

**Issue by ezolotko** [OmniSharp/csharp-language-server-protocol#170]
Hello, and thank you for working on this project.

Which features of LSP are currently supported for client-side use?

From looking at ClientCapabilities, I can see only Synchronization, Hover, and Completion capabilities are supported at the moment. TextDocumentClient class also has methods for these three features only. On the other hand, in the Protocol project, I see a lot of classes (auto-generated?) seemingly covering all of the protocol.

How could I use some of the features which are not present in the ClientCapabilities and TextDocumentClient at the moment? For example, if I wanted to use SignatureHelp on the client, what would be required to add to the Client library?

**Comment by tintoy** [comment]
Yes, definitely - I just hadn’t got around to implementing the other features since it wasn’t being used. I kinda wish I’d done them as extension methods to make them easier to add but that would be a breaking change.

Adding a new client is still not much work (see the “Clients” folder under “Client” for examples). Feel free to open a PR or if you’re not sure how to proceed I can have a go at adding it this afternoon if you can post a link to the mode classes for the messages you want to handle :)

**Comment by ezolotko** [comment]
Hi, thank you for the quick reply. I am aiming to connect a .NET client to clangd server. Clangd has the following list of [server capabilities](https://clang.llvm.org/extra/clangd/Features.html#complete-list-of-features) (I sorted them by (a subjective) importance):

- Completion
- Signature Help
- Source hover
- Diagnostics
- Go to Definition
- Document Highlights
- Find References
- Formatting
- Fix-its
- Rename
- Document Symbols
- Workspace Symbols

For sure I will not be up to speed to produce a PR as fast as "this afternoon" :), so if you could add some of these features I will greatly appreciate this. Otherwise I will try to see if I can do them by myself.

**Comment by tintoy** [comment]
No problem I’ll get started tomorrow and see what I can come up with :)

**Comment by tintoy** [comment]
CC: @david-driscoll @TylerLeonhardt - does https://github.com/tintoy/csharp-language-server-protocol/commit/2e2cae31ea794efdfda1b03f46bd50ea933ab823 look reasonable to you? If so, I'll open a PR sometime tomorrow :)

**Comment by TylerLeonhardt** [comment]
The API looks solid. I'll let @david-driscoll be the judge of the underlying implementation.

**Comment by ezolotko** [comment]
I submitted #184 for Signature help support. If this turns out OK I could try to add all the remaining features from the list above and submit a PR.

**Comment by david-driscoll** [comment]
@ezolotko There is a new language client that should have full support for all the features now, there are some breaking changes along the way but things now integrate nice and cleanly togetrher.

**Comment by ezolotko** [comment]
@david-driscoll cool, thank you! I am closing this issue then.
