### ISSUE TITLE
DiagnosticRelatedInformation Location should be an Location object

### ISSUE THREAD

**Issue by drsoran** [OmniSharp/csharp-language-server-protocol#175]
Currently the `DiagnosticRelatedInformation.Location` property is a `string`. I think this is not correct in sense of Language Server Protocol. I think they expect `Location` to be an `Location` object with URI and Range.

I tried to pass a string but VS Code then displays related messages as:

**undefined(undefined, undefined): message**

**Comment by drsoran** [comment]
#176

**Comment by david-driscoll** [comment]
@drsoran I think you're correct.  Thanks for the find!
