### ISSUE TITLE
ILoggingBuilder enhancements

### ISSUE THREAD

**Issue by mholo65** [OmniSharp/csharp-language-server-protocol#185]
Now that https://github.com/OmniSharp/csharp-language-server-protocol/pull/182 is merged, we should add a `ILoggingBuilder` extension for adding LanguageServerLoggerProvider.

We should also read the minimum logging level from the one provided via `SetMinimumLevel` on the LoggingBuilder.

//cc @david-driscoll

**Comment by mholo65** [comment]
And remove the `UseDefaultLoggingProvider` from LanguageServerOptions.

**Comment by david-driscoll** [comment]
I say doooooo eeeiiiiitttt

**Comment by david-driscoll** [comment]
I think the goal here has been accomplished for the most part.
