### ISSUE TITLE
DidChangeWatchedFilesRegistrationOptions not available

### ISSUE THREAD

**Issue by AdrianG-OSS** [OmniSharp/csharp-language-server-protocol#197]
The specs lists DidChangeWatchedFilesRegistrationOptions as an option to register for external file events (including file deletion and creation in the workspace). But I cannot find this implemented in the API anywhere.

How do you do filewatching without file registration?

**Comment by fantasydr** [comment]
You could implement the option by yourself, simply added this definition in your code.
```
    class DidChangeWatchedFilesRegistrationOptions
    {
        public FileSystemWatcher[] Watchers { get; set; }
    }

    public class FileSystemWatcher
    {
        public string GlobPattern { get; set; }
        public int Kind { get; set; }
    }
```

And impl your handler interface like this:
```
        object IRegistration<object>.GetRegistrationOptions()
        {
            return new DidChangeWatchedFilesRegistrationOptions
            {
                Watchers = new FileSystemWatcher[]
                {
                    new FileSystemWatcher{
                        GlobPattern = "**/*.myscript", // your own glob string
                        Kind = 7,  // all kind of event, create|delete|change
                    }
                },
            };
        }
```

**Comment by david-driscoll** [comment]
#186 will address this, it's relatively new to the spec.  I just have to finalize updates to that PR once I pull in the configuration changes.

**Comment by david-driscoll** [comment]
This is now in place.  Let us know if you find any problems.
