### ISSUE TITLE
Some Links

### ISSUE THREAD

**Issue by Lercher** [OmniSharp/csharp-language-server-protocol#2]
Hi,

Cool to see a .Net implementation of the LanguageServer Protocol. I'm searching for something like this for Coco/R parsers for nearly a year now. Thanks.

I just wanted to offer my 5 cents:
* https://github.com/DotJoshJohnson/vscode-dotnet (similar intent, but apparently not active anymore)
* https://github.com/Astn/JSON-RPC.NET/ (it's probably useful, to use an existing JSON RPC implementation, however it's only for net40 and mono)

Best regards
Martin

**Comment by david-driscoll** [comment]
👍 I had looked at the latter but if I recall there were some differences.  However I'm not yet 100% sold on this truly supporting the full Json RPC spec, once I fully realized the duality relationship between the "client" and the "server".

In some scenarios the editor (`vscode`, `emacs`, `eclipse`, etc) is the "client" in other's is actually the "server".  And the reverse is true for the server itself.  Sadly this is leaking into the JsonRpc code a little bit, so my feeling is I'll probably internalize those namespaces, or make them part of the same nuget package until that can be properly sorted.

**Comment by Lercher** [comment]
Just a link to the protocol documentation:
* https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md
