### ISSUE TITLE
Could you post your OmniSharp log for me? I'm wondering if the OmniSharp server is dying and restarting, which causes the errors to disappear.

### ISSUE THREAD

**Issue by ghost** [OmniSharp/csharp-language-server-protocol#204]
Could you post your OmniSharp log for me? I'm wondering if the OmniSharp server is dying and restarting, which causes the errors to disappear.
1. Open Visual Studio Code and reproduce the problem.
2. Select View->Output to display the Output pane
3. At the top-right corner of the Output pane, select "OmniSharp Log" from the dropdown.
4. Copy and paste the content into this issue.

_Originally posted by @DustinCampbell in https://github.com/OmniSharp/omnisharp-vscode/issues/941#issuecomment-260727237_

**Comment by david-driscoll** [comment]
I don't think this applies to repo.
