### ISSUE TITLE
Support for semantic tokens

### ISSUE THREAD

**Issue by koliyo** [OmniSharp/csharp-language-server-protocol#221]
Thanks a lot for this LSP library, it has been really helpful!

Have you started looking at implementing semantic tokens in the API?

- https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview
- https://github.com/microsoft/vscode-extension-samples

This seems really useful to be able to avoid the messy tmLanguage handling.

**Comment by david-driscoll** [comment]
This is something we should really look at, I see the vscode language node does support it, so it's something we can look at.

**Comment by david-driscoll** [comment]
I have added the two current proposals, keep in mind that they can change and there could be breaking changes to those types!  Once the proposal lands they'll get moved and the [Obsolete] attributes removed!
