### ISSUE TITLE
NPE in TextDocumentHandler

### ISSUE THREAD

**Issue by aBothe** [OmniSharp/csharp-language-server-protocol#240]
Hey there,

I'm trying to set up a LanguageServer having a custom DefinitionHandler.
This handler currently features a DefinitionRegistrationOptions config object with a DocumentSelector set to null (it's just still the default - I'll define it soon).

When trying to start the LanguageServer in one of my tests, it just didn't want to fully initialize.
I manually stepped through LanguageServer code to find out what's throwing an exception there.

Turns out, it's an NullPointerException in `TextDocumentHandler.GetHandler`:
https://github.com/OmniSharp/csharp-language-server-protocol/blob/79b10564b705e82496e6f0da7af4c64e9cef73f8/src/Server/Matchers/TextDocumentMatcher.cs#L82

There might be a `?` missing in the second clause, as it's evaluating said second expression as soon as registrationOptions is not null - but DocumentSelector might be.

My code was: 
```
public DDefinitionHandler(ProgressManager progressManager)
            : base(new DefinitionRegistrationOptions(), progressManager)
        {
        }
```

Thanks for your project!

**Comment by david-driscoll** [comment]
Thanks @aBothe 

I think you might be right, it's very possible the registrations options is null in that scenario.   After this next big change I'll look at adding that in.

**Comment by david-driscoll** [comment]
I will get a fix in for this, I think it is still there looking at the code I just need to create a test case.

**Comment by david-driscoll** [comment]
I have added a test to my latest commit, to confirm this appears to be working as expected.  Let me know if you have any more problems!
