### ISSUE TITLE
Serve through a websocket

### ISSUE THREAD

**Issue by centellenc** [OmniSharp/csharp-language-server-protocol#254]
I have added the question in stackoverflow ([serve-csharp-language-server-protocol-instance-through-a-web-socket](https://stackoverflow.com/questions/62267691/serve-csharp-language-server-protocol-instance-through-a-web-socket)) but I believe it makes sense to link it from here as well. 

Does anyone know of any example?

**Comment by david-driscoll** [comment]
I do have an old example here: https://github.com/david-driscoll/lsp-playing/blob/master/monaco/src/client.ts

Not sure how relevant it is now.
