### ISSUE TITLE
 How to start the server with standard input and output in version 0.17+？

### ISSUE THREAD

**Issue by pengsongkun741** [OmniSharp/csharp-language-server-protocol#255]
/// <summary>
        ///     Create a new <see cref="LanguageClient"/>.
        /// </summary>
        /// <param name="loggerFactory">
        ///     The factory for loggers used by the client and its components.
        /// </param>
        /// <param name="serverStartInfo">
        ///     A <see cref="ProcessStartInfo"/> describing how to start the server process.
        /// </param>
        public LanguageClient(ILoggerFactory loggerFactory, ProcessStartInfo serverStartInfo)
            : this(loggerFactory, new StdioServerProcess(loggerFactory, serverStartInfo))
        {
        }
LanguageClient can start the server in this way in version 0.16. However, in the 0.17+ version, the server cannot be found by standard input and output.

I am currently interacting with the vscode LSP server through the Omnisarp LSP Client. In version 0.16, I tried to use standard input and output to achieve communication. In version 0.17, I see that there is a pipeline, but I still can't correctly communicate through the pipeline.

If I want to continue to use standard input and output communication, are there any good suggestions? Thank you!

**Comment by david-driscoll** [comment]
The sample server accomplishes with:
https://github.com/OmniSharp/csharp-language-server-protocol/blob/master/sample/SampleServer/Program.cs#L40-L41

For the client the code is identical to the server in that respect.

Also I have a few tests that demonstrate STDIO and named pipes (not comprehensive, I didn't try to do sockets, or a few other things yet...)
https://github.com/OmniSharp/csharp-language-server-protocol/blob/master/test/JsonRpc.Tests/ConnectionTests.cs#L26-L34

**Comment by pengsongkun741** [comment]
Thank you very much. I have solved the problem!

I started the LSP server as a process . Then converting ProcessBaseStream to type  PipeStream .Add the client's initialization Settings.The communication of standard input and output is completed . Thank you for your help!

```
            var process = new Process
            {
                StartInfo = processStartInfo,
                EnableRaisingEvents = true
            };

            process.Start();

            var clientOption = new Action<LanguageClientOptions>(client => { });

            var pipeReader = PipeReader.Create(process.StandardOutput.BaseStream);

            var pipeWriter = PipeWriter.Create(process.StandardInput.BaseStream);

            _client = LanguageClient.PreInit(options =>
             {
                 options.WithInput(pipeReader).WithOutput(pipeWriter);

                 clientOption(options);
             });

            await _client.Initialize(cancellationToken);
