### ISSUE TITLE
With the new semantic tokens, how do you trigger the client from the server to re-evaluate tokens?

### ISSUE THREAD

**Issue by Pyromuffin** [OmniSharp/csharp-language-server-protocol#257]
I'm running into a situation where I'm editing a header file, which may change the value of tokens in a file that includes it. I'm finding that the file that includes the value has stale token information when the header changes, and I don't know what to do from the server side to tell the client that it needs to re-request the tokens for a file that had changes made via an include.

i checked out omnisharp-roslyn for c# in vscode and it just seems to refresh every few seconds or so, but I don't even think omnisharp-roslyn is using LSP. Maybe this is a better question for LSP in general, but I have no idea where to even ask questions about that.

Any pointers would be appreciated, it's fully possible that i'm just missing something in the LSP specification, however, the proposed 3.16 page https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/ uhhh just doesn't have any information on it about semantic tokens.

Thanks,
Kelly

**Comment by david-driscoll** [comment]
Yeah the proposal wasn't completed, it is now, but I need to make a few adjustments to get it all working.

**Comment by david-driscoll** [comment]
This has been added to the proposed version of the spec, there is now a notification the server can send to the client to re-evaluate semantic tokens.
