### ISSUE TITLE
Documentation: How do I send a response?

### ISSUE THREAD

**Issue by itmuckel** [OmniSharp/csharp-language-server-protocol#259]
In [the specs](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize) it says that the server should answer to an InitializeRequest with its capabilities and then send a Initialized Notification.

How can I do that? The Initialize Delegate has no return value. Is this all somehow handled by the framework? Are there simple projects I can look at to get an understanding of how this works?

This maybe helps with the open issue about documentation. 😄

**Comment by itmuckel** [comment]
Okay, it seems that lsp4intellij is a bit broken in that area. VS Code seems to work fine.

**Comment by david-driscoll** [comment]
The startup negotiation is handled by the library for you, so you don't have to do anything to interact with it.  It's possible there are issues with lsp4intellij.

I would love to get more information so that I can try and figure out the best way to fix it!

There is more work to be done to handle custom extensions to the protocol (with additional data in the startup process) but this doesn't affect most cases.

**Comment by itmuckel** [comment]
I use [this plugin](https://github.com/gtache/intellij-lsp) (sorry, not lsp4intellij, but it is built upon that). Communication seems to work, but apparently intellij-lsp doesn't get the answer it wants from the server. Here are the logs:

```
[Trace - 07:33:40 nachm.] Sending request 'initialize - (1)'
Params: {
  "processId": null,
  "rootUri": "file:///C:/Users/Admin/Documents/Code/csharp/DotLisp/",
  "capabilities": {
    "workspace": {
      "applyEdit": true,
      "workspaceEdit": {
        "documentChanges": true
      },
      "didChangeConfiguration": {},
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "symbol": {},
      "executeCommand": {},
      "workspaceFolders": false,
      "configuration": true
    },
    "textDocument": {
      "synchronization": {
        "willSave": true,
        "willSaveWaitUntil": true,
        "didSave": true
      },
      "completion": {
        "completionItem": {
          "snippetSupport": true
        }
      },
      "hover": {},
      "signatureHelp": {},
      "references": {},
      "documentHighlight": {},
      "formatting": {},
      "rangeFormatting": {},
      "onTypeFormatting": {},
      "definition": {},
      "codeAction": {},
      "rename": {
        "prepareSupport": true,
        "dynamicRegistration": false
      },
      "semanticHighlightingCapabilities": {
        "semanticHighlighting": false
      }
    }
  }
}


[Trace - 07:33:40 nachm.] Received notification 'window/logMessage'
Params: {
  "type": 3,
  "message": "DotLispLsp.Foo: Configuring | "
}


[Trace - 07:33:40 nachm.] Received notification 'window/logMessage'
Params: {
  "type": 3,
  "message": "OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter: Finding descriptor for initialize | Method\u003d\u0027initialize\u0027"
}


[Trace - 07:33:40 nachm.] Received notification 'window/logMessage'
Params: {
  "type": 3,
  "message": "OmniSharp.Extensions.JsonRpc.ProcessScheduler: Queueing Serial:initialize:1 request for processing | Type\u003d\u0027Serial\u0027 Name\u003d\u0027initialize:1\u0027"
}


[Trace - 07:33:40 nachm.] Received notification 'window/logMessage'
Params: {
  "type": 3,
  "message": "OmniSharp.Extensions.JsonRpc.InputHandler: Starting: Processing request initialize 1 | Method\u003d\u0027initialize\u0027 ResponseId\u003d\u00271\u0027"
}


[Trace - 07:33:40 nachm.] Received notification 'window/logMessage'
Params: {
  "type": 3,
  "message": "OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter: Starting: Routing Request (1) initialize | Id\u003d\u00271\u0027 Method\u003d\u0027initialize\u0027"
}


[Trace - 07:33:40 nachm.] Received notification 'window/logMessage'
Params: {
  "type": 3,
  "message": "DotLispLsp.Foo: OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams | "
}


[Trace - 07:33:50 nachm.] Sending request 'shutdown - (2)'
Params: null
```

Looks like the server just sends the some logMessages and then intellij-lsp decides to shutdown the server.

I just use the example server in this repository, maybe I need to change it, so it responds with its capabilities? 🤔

**Comment by itmuckel** [comment]
Oh, wow, it works now.

I think the reason that no response was sent to the client was that there were no real server capabilities to report. I dumbed down the sample server a bit (removing the chained OnXYZ functions in Program.cs) and added some registration options to the handlers I use. I think those registration options made the difference.

So all in all I think the edge case I discovered is that the LS should respond with capabilities even though none have been registered, just to finish the initialization process.

Here is [my repo](https://github.com/itmuckel/DotLisp).

Here is the response:
```
[Trace - 00:22:46 vorm.] Received response 'initialize - (1)' in 1150ms
Result: {
  "capabilities": {
    "textDocumentSync": {
      "openClose": true,
      "change": 1,
      "willSave": false,
      "willSaveWaitUntil": false,
      "save": {
        "includeText": true
      }
    },
    "completionProvider": {
      "resolveProvider": true
    },
    "experimental": {}
  }
}
```

Here is the result in IntelliJ:

![grafik](https://user-images.githubusercontent.com/18561536/88345041-5de5cc00-cd45-11ea-9d19-aac3fc7d54ad.png)

Here it is in VS Code:

![grafik](https://user-images.githubusercontent.com/18561536/88345079-7c4bc780-cd45-11ea-8c74-934250732ae8.png)

VS Code probably supports more features than the intellij-lsp plugin, so I get the static test doc string there.

@david-driscoll Can you confirm that no response to the initialize request is sent, when no capabilities are registered?

**Comment by david-driscoll** [comment]
We should still respond even if there are no capabilities found.

**Comment by david-driscoll** [comment]
It's possible we don't however, I might try and add a test in to verify that.

**Comment by david-driscoll** [comment]
@itmuckel let me know if you're still having issues and I can re-open this.
