### ISSUE TITLE
Support dependency injection?

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/csharp-language-server-protocol#28]
Should we support dependency injection?

The initial goal was to be framework / container agnostic, hence the support for handlers being disposable and specifically instance based, etc.

Does it make sense to introduce dependency injection at all?  We could use something like `IServiceProvider` to keep it simple, but might complicate matters when you get to the "conforming containers" debate.

**Comment by tintoy** [comment]
Personally I've found DI to be super-useful for something like a language server, especially since the list of "provider"-type components changes frequently and can benefit from discovery-like behaviour:

https://github.com/tintoy/msbuild-project-tools-vscode/blob/master/src/LanguageServer.Engine/LanguageServerModule.cs#L49-L61

**Comment by tintoy** [comment]
Another example:

https://github.com/tintoy/msbuild-project-tools-vscode/blob/master/src/LanguageServer.Engine/LanguageServerModule.cs#L92-L112

**Comment by tintoy** [comment]
Sure, you can't make every consumer happy all of the time, but if you give them the option to use DI without forcing it on them then maybe it's an acceptable trade-off?

Might be going a bit far to develop the whole `WebHostBuilder` and `IAppBuilder` abstraction, but there's probably a happy medium in there somewhere :)

**Comment by david-driscoll** [comment]
Yeah the simple injector case was what I was thinking about.  For now I'm on the fence, and I'll probably stay there for a while.  We don't have a need (yet!) to replace all the internal classes.  This is subject to change and DI may come in then.

**Comment by david-driscoll** [comment]
This has been added internally, there are some rough edges (integrating with an external container can't be done yet...)
