### ISSUE TITLE
vscode (maybe lsp?): Registering dynamically and statically causes duplicate requests

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/csharp-language-server-protocol#30]
So `0.3.0` fixed an issue with the client options providers not working as expected.

This has raised a new issue, where providers registered via the static means (at client return) are also called again when dynamically registered.

Need to investigate this issue and see if it's a problem in LSP implementation, the vscode lsp implementation or just a regular bug.

cc @tintoy

**Comment by tintoy** [comment]
Probably `vscode-languageclient`, BTW - I found I got double-called for stuff like hover and completions if I added a `DocumentSelector` twice on the `LanguageClient` in my extension :)
