### ISSUE TITLE
`is null` Textmate Colorization Issue

### ISSUE THREAD

**Issue by TanayParikh** [OmniSharp/csharp-language-server-protocol#322]
VS Code:
![image](https://user-images.githubusercontent.com/14852843/90698920-d0f43c80-e236-11ea-993e-9b9e36529e83.png)

VS:
![image](https://user-images.githubusercontent.com/14852843/90698946-e0738580-e236-11ea-87fe-8fad1248ad8e.png)

For VSCode I would think both `null`s would be the same color.

Please let me know if this isn't the right location for this issue.

**Comment by david-driscoll** [comment]
This should probably go over to https://github.com/OmniSharp/vscode-textmate or https://github.com/OmniSharp/omnisharp-vscode
