### ISSUE TITLE
Conversion of unsupported `ClientCapabilities` is incompatible with other LSP implementations.

### ISSUE THREAD

**Issue by adityasharad** [OmniSharp/csharp-language-server-protocol#35]
Client capabilities in the LSP are usually specified as an optional wrapper around a boolean value, e.g.  the `workspaceEdit` capability in `WorkspaceClientCapabilities` is a wrapper around a `documentChanges` boolean. The possible values here are: wrapper around `true`, wrapper around `false`, or a non-existent or `null` value to indicate the capability is not supported/recognised.

I observe that the [default behaviour of the `SupportsConverter`](https://github.com/OmniSharp/csharp-language-server-protocol/blob/master/src/Lsp/Converters/SupportsConverter.cs#L38) is to always provide the value `false` instead of `null` when the capability is not supported. This makes the OmniSharp protocol implementation incompatible with language server implementations that expect an object wrapper around a boolean (instead of just a boolean) in capability fields such as `WorkspaceClientCapabilities.workspaceEdit`.

The example where I observed this incompatibility used [Eclipse LSP4J](https://github.com/eclipse/lsp4j) for the server, and the [.NET language client](https://github.com/tintoy/dotnet-language-client) (which relies on OmniSharp for the protocol implementation) as the client.

**Comment by david-driscoll** [comment]
What would be the preferred solution?

We can serialize out the value as null, or as per the spec just omit any property that isn't supported?

**Comment by adityasharad** [comment]
I suggest following the spec and omitting the unsupported property. Setting it to `null` will probably be incompatible with LSP implementations (if any) that do not handle `null` object values for capabilities. I am open to hearing the views of others with more experience using protocol implementations, but that is the preferred solution for my uses.
