### ISSUE TITLE
Consider making Position(And possibly Range?) IComparable and adding more operator overloads

### ISSUE THREAD

**Issue by ajaybhargavb** [OmniSharp/csharp-language-server-protocol#376]
It is fairly common to want to check whether a position appears before or after another and it would be nice to have them be easily comparable([like this](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Text/LinePosition.cs#L131)) instead of having to check the line and character separately.

Here is [an example](https://github.com/dotnet/aspnetcore-tooling/blob/fbe96281b6b8723f3b45d1456f0c0fa737e65025/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs#L67) of where this might be useful.

**Comment by david-driscoll** [comment]
I think that makes sense.

Should we apply the same thing to `Range` as well?

**Comment by ajaybhargavb** [comment]
> Should we apply the same thing to Range as well?

We haven't found the need for it yet. Maybe not given Roslyn doesn't do that either, https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Text/LinePositionSpan.cs.

**Comment by ajaybhargavb** [comment]
Thanks @david-driscoll
