### ISSUE TITLE
DocumentColorHandler should return ColorInformation but returns ColorPresentation

### ISSUE THREAD

**Issue by gzroger** [OmniSharp/csharp-language-server-protocol#381]
IDocumentColorHandler/DocumentColorHandler results Container<ColorPresentation> but according to ls specs (https://microsoft.github.io/language-server-protocol/specification#textDocument_documentColor) it should return ColorInformation. 

textDocument/colorPresentation should return ColorPresentation which is correct in ColorPresentationHandler

Btw ColorInformation is present in the code but not used anywhere.

**Comment by david-driscoll** [comment]
sounds like a bug!
