### ISSUE TITLE
textDocument/semanticTokens/range async implementation

### ISSUE THREAD

**Issue by Elringus** [OmniSharp/csharp-language-server-protocol#389]
Hey there, 

I've implemented `SemanticTokensHandlerBase.Tokenize()` method in the following way hoping it'll handle tokenize requests without blocking the server:

```csharp
protected override async Task Tokenize (SemanticTokensBuilder builder,
    ITextDocumentIdentifierParams identifier, CancellationToken cancellationToken)
{
    var document = documentManager.GetDocument(identifier.TextDocument.Uri);
    var lines = identifier is SemanticTokensRangeParams rangeParams 
        ? document.GetLinesRange(rangeParams.Range.Start.Line, rangeParams.Range.End.Line) : document.Lines;
    await Task.Run(TokenizeLines, cancellationToken).ConfigureAwait(false);

    void TokenizeLines ()
    {
        foreach (var line in lines)
            TokenizeSymbol(line, builder);
    }
}
```

When opening a large file in VS Code, it correctly receives the range request, but at the same time it receives a full request, which seem to block handling of the range one, making semantic highlight appear only after the full request completes. 

Am I doing something wrong here? I've tried looking for reference `semanticTokens/range` implementations in the existing OmniSharp projects, but wasn't able to find any.

**Comment by david-driscoll** [comment]
So tokenize is pretty naive, and basically just expects you to retokenize the entire file, and then it will return the diff.  However all of the handler methods are virtual, so you can override them to do a specific behavior if you want.

This is something I want to explore in the future, but there are a million different ways tokenization can be handled.  In addition in C# for example if you change something from a `class` to an `interface` semantically it's going to change everything in the file potentially, even if the update was only made on one line.

**Comment by Elringus** [comment]
Ah, I see. I had an impression it'd work similar to `textDocument/didChange` with only the changed content range. Thank you for the answer!
