### ISSUE TITLE
shutdown and exit methods not found

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/csharp-language-server-protocol#39]
See also #38

**Comment by david-driscoll** [comment]
@tintoy I think the shutdown handler is being removed before the server shutdown is complete... there by causing it to not be found.  same for exit.

**Comment by david-driscoll** [comment]
Are you able to test something using a local build of the lsp package?

change the following lines:
https://github.com/OmniSharp/csharp-language-server-protocol/blob/master/src/Lsp/LanguageServer.cs#L54-L56

To 
```csharp
AddHandlers(_shutdownHandler, _exitHandler);

            _disposable.Add(
                AddHandlers(this, new CancelRequestHandler(_requestRouter))
            );
```

**Comment by tintoy** [comment]
Sure, give me 20 mins and I'll pull it down and have a go.

**Comment by tintoy** [comment]
Nope, doesn't work. The reason is because the handler descriptors are clashing due to matching on handler type instead of something like handler type and method name and so they're never added to the hash set in `HandlerCollection.Add`.

**Comment by david-driscoll** [comment]
Doh! You're right...
