### ISSUE TITLE
Should the registerCapability request refer to the semantic tokens capability as `textDocument/semanticTokens` or `textDocument/semanticTokens/full`?

### ISSUE THREAD

**Issue by anthony-c-martin** [OmniSharp/csharp-language-server-protocol#397]
We're using Omnisharp.Extensions.LanguageServer (which is great, by the way!) to build a language server which is consumed by the vscode-languageclient NPM package. Recently we were upgraded from [7.0.0-next.10](https://www.npmjs.com/package/vscode-languageclient/v/7.0.0-next.10) to [7.0.0-next.12](https://www.npmjs.com/package/vscode-languageclient/v/7.0.0-next.12), which has renamed the `textDocument/semanticTokens/full` capability to `textDocument/semanticTokens`, and hits an error when the Omnisharp server calls `client/registerCapability` with the former. It also seems like the LSP spec has been recently updated accordingly.

Do you happen to know what the correct behavior is? If it looks more like an issue with the client library, feel free to close this!

**Comment by david-driscoll** [comment]
The spec changed mid-way through and updated namings, so I did the same.  These have been set in the latest version `v0.8.1`.  That was an issue I had encountered, a later version had a fix for it if I recall.

**Comment by anthony-c-martin** [comment]
> The spec changed mid-way through and updated namings, so I did the same. These have been set in the latest version `v0.8.1`. That was an issue I had encountered, a later version had a fix for it if I recall.

Ah, makes sense. I guess that's to be expected with a proposed feature and all! I've tried pulling down the latest `v.0.18.1` nuget, but I'm still seeing the same behavior. Is there anything special I need to do to enable it?

**Comment by david-driscoll** [comment]
hmmm I wonder if they changed the names again, I'll take a look tonight.

**Comment by david-driscoll** [comment]
Okay... so they've introduced this new Registration Type concept... le sigh

https://github.com/microsoft/vscode-languageserver-node/blob/release/client/7.0.0-next.12/protocol/src/common/protocol.semanticTokens.ts#L245

I will investigate and see what needs to change... I'm a sad panda...

**Comment by anthony-c-martin** [comment]
Thanks very much for investigating and fixing this!
