### ISSUE TITLE
PrepareRename does not work with VSCode client

### ISSUE THREAD

**Issue by pablostu** [OmniSharp/csharp-language-server-protocol#409]
I'm trying to activate PrepareRename handler on server side.
"PrepareRename" capability is nowhere registered as feature (especially not as dynamic feature) on client side in VS Code LSP Client. It is only part of RenameFeature.

So how to enable PrepareRename on server side?
a) if no handler (IPrepareRenameHandler not implemented or not registered) is registered, then even if client sends PrepareRename request, no descriptor will be found on server.
b) if handler is implemented and registered as dynamic feature, then client rejects it, because Client does not know dynamic feature: prepareRename.

Do I need to secretly register handler on LSP server so that client doesn't know about it? and then PrepareRequest can be answered correctly?
Or do I need to make client "aware" of its hidden feature prepareRename?

**Comment by david-driscoll** [comment]
Prepare rename is something I've needed to look at, thank you for bringing it up.  It needs to be built out similar to how Semantic Tokens is now handled, so I might have to make some breaking changes for that.  However they probably aren't huge breaking changes, and if it hasn't worked anyway... what are you breaking? 😄

**Comment by david-driscoll** [comment]
I stand corrected, this is something I had looked at, and you should just be able to implement the IPrepareRenameHandler on a handler (it could even be your rename handler), and then if the client supports prepare rename it'll call it.

You just need to set `PrepareProvider` to true on `RenameRegistrationOptions` and things should just work.

**Comment by david-driscoll** [comment]
I am going to add additional assertions to these tests, but they do exercise prepare rename a little bit.
https://github.com/OmniSharp/csharp-language-server-protocol/blob/master/test/Lsp.Tests/Integration/RenameTests.cs

**Comment by pablostu** [comment]
Thanks for answering. That is also my understanding how it should work.
Implementation of IPrepareRenameHandler will lead to registration of this capability and server will send request with this dynamic capability to the client:
   `   
           {
            "id": "c0380365-0955-4e19-8abb-20ea01047e1d",
            "method": "textDocument/rename",
            "registerOptions": {
                "prepareProvider": true,
                "workDoneProgress": true,
                "documentSelector": [
                    {
                        "language": "st"
                    }
                ]
            }
        },
        {
            "id": "a4b38c46-b979-412a-b9a4-301ab502d0b9",
            "method": "textDocument/prepareRename",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "st"
                    }
                ]
            }
        },
	`	
		
but VSCode client does not support PrepareRename as "standalone dynamic capability", it seems to be more part of rename. VSCode client does not announce prepareRename as its dynamic capability, in initialize request
there is only "rename" with its "prepareSupport" mentioned.
	`	
		     "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
      ` 

So if the server responds with prepareRename capability, VS Code rejects it.

**Comment by david-driscoll** [comment]
Gotcha, okay I can make that fix I think, I'll look at it tonight.
