### ISSUE TITLE
The given key 'insertFinalNewline' was not present in the dictionary

### ISSUE THREAD

**Issue by shenglol** [OmniSharp/csharp-language-server-protocol#411]
Got this error when requesting document formatting with no `insertFinalNewline` set in FormattingOptions:
```
Internal Error - System.Collections.Generic.KeyNotFoundException: The given key 'insertFinalNewline' was not present in the dictionary.
```

According to the LSP docs `trimTrailingWhitespace`, `insertFinalNewline` and `trimFinalNewlines` are optional, however it seems the OmniSharp implementation just assumes they are always in the dictionary? Should we check their existence before accessing the keys?

https://github.com/OmniSharp/csharp-language-server-protocol/blob/6371386ee90dde8a1c419f3dc8fc94e0c1bc35f0/src/Protocol/Models/FormattingOptions.cs#L40

**Comment by david-driscoll** [comment]
looks like a bug, it should be using `TryGetValue` instead.
