### ISSUE TITLE
Bug in IColorPresentationHandler

### ISSUE THREAD

**Issue by JoeDimo** [OmniSharp/csharp-language-server-protocol#455]
Hello, I have recently updated from 17.4 to 18.1 and I believe there is bug somewhere regarding the `IColorPresentationHandler`. 

My `DocumentColorPresentationHandler` implements `IColorPresentationHandler` and ever since I updated, this handler seems to break other handlers and more generally, my extension that interacts with my server. For example, when I try to use this handler, my `DidOpenTextDocument` event in my `TextDocumentSyncHandler` never fires, my SemanticTokensHandler never hits, etc. When I comment it out, all of my handlers work, including my `DocumentColorHandler`, which implements `IDocumentColorHandler` (until I try to make a `textDocument/colorPresentation` request, of course). So I don't think the problem is related to the `IDocumentColorHandler`.

This leads me to believe the issue has something to do with `IColorPresentationHandler`.

One thing I noticed is that even though the LSP Specification's entry for [Color Presentation Request](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_colorPresentation) states that "This request has no special capabilities and registration options since it is send as a resolve request for the `textDocument/documentColor` request," the `IColorPresentationHandler` interface requires us to implement both `DocumentColorRegistrationOptions` and `ColorProviderCapability` in our color presentation handlers, which are the same type of registration options and capability that the `IDocumentColorHandler` interface requires us to have for our implementations of it, which I found strange. I'm not sure if this is supposed to be this way or not, but I would think that its not, and it's just something I noticed and thought may have something to do with the `IColorPresentationHandler` causing problems.

**Comment by david-driscoll** [comment]
I can take a look at what might be going on.
