### ISSUE TITLE
Lang Server Client in C#

### ISSUE THREAD

**Issue by jayonsoftware** [OmniSharp/csharp-language-server-protocol#46]
I am new to LSP and looks like all the example clients are in Node (JS / TS). Before I reinvent the wheel, is they're an LSP client sample anyone is aware of ?

Thanks

Jay

**Comment by jayonsoftware** [comment]
Interesting timing, just saw this now [https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension), a day old :-)

**Comment by tintoy** [comment]
https://github.com/tintoy/dotnet-language-client :)
Interesting to see they are adding an LSP client for VS; my repo includes an example of that but it used to be kinda painful before the most recent release of the full .NET framework (.NET Standard dependencies).

**Comment by tintoy** [comment]
BTW, I'm in the process of contributing that client into this repository (but feel free to use it from there in the meanwhile).

**Comment by david-driscoll** [comment]
And feel free to chat on slack (if that's your thing) I'd like to hear more about this development. https://omnisharp.herokuapp.com/

**Comment by japj** [comment]
Is anyone working on a visual studio sample testextension like the atom/vscode one now that VS2017 Update8 has native LSP support?
