### ISSUE TITLE
DiagnosticRelatedInformation without Location

### ISSUE THREAD

**Issue by OGMichel** [OmniSharp/csharp-language-server-protocol#542]
Hello, 

I have a question/remark concerning the DiagnosticRelatedInformation class.

I want to use the RelatedInformation of the Diagnostic class to return detailed information on a diagnostic.
The problem I have is the following : my informations are pure message and don't have to be linked to a specific Location.

I tried letting the Location null but VSCode stopped displaying any diagnostic as if it never received them.
I tried initializing the Location with an empty object but VSCode make the nullity of the Uri and Range visible and still consider the message to contain a clickable link
![image](https://user-images.githubusercontent.com/66632133/110961204-d094cd80-834f-11eb-8055-83add5f98f0c.png)
![image](https://user-images.githubusercontent.com/66632133/110960700-506e6800-834f-11eb-85f8-2ebbd78b1ced.png)

The best solution I have for now is to fill the Locations with the information of the Diagnostic they are related too.

Is there any other solution I missed ?

Thank you for your help.

**Comment by david-driscoll** [comment]
Based on the spec the location is currently required: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#diagnostic. Nothing we can really do to change that unfortunately.

**Comment by OGMichel** [comment]
That's what I feared. Thank you for your help.
