### ISSUE TITLE
Replacement for ServerProcess/StdioServerProcess/NamedPipeServerProcess in 0.19.0

### ISSUE THREAD

**Issue by yevgeni-zolotko** [OmniSharp/csharp-language-server-protocol#555]
Hello,
We are trying to migrate from the version 0.15.0 to 0.19.0.
One of the breaking changes we encountered is the absence of ServerProcess/StdioServerProcess/NamedPipeServerProcess classes. So far I didn't find a replacement for their functionality. Could you please point me to the right direction (a sample code perhaps) on how to start up a server process and connect a LanguageClient to it.
Thank you.

**Comment by david-driscoll** [comment]
You can reference the old code for a place of where to start (eg https://github.com/OmniSharp/csharp-language-server-protocol/blob/c8cca3353760b35185e2dad2ce6e27ff4ce65fe4/src/Client/Processes/StdioServerProcess.cs)

And then you just pass the expected pipes or streams into the options.
Something like this https://github.com/OmniSharp/csharp-language-server-protocol/blob/1b6788df2600083c28811913a221ccac7b1d72c9/test/Client.Tests/PipeServerTestBase.cs#L65-L72

**Comment by yevgeni-zolotko** [comment]
Thank you, with this pointer I was able to start and initialize a server process.
