### ISSUE TITLE
Client request which returns a list like 'workspace/symbol', example, suggestion

### ISSUE THREAD

**Issue by Helmut-Ortmann** [OmniSharp/csharp-language-server-protocol#56]
Hi,

I want to use C# to request a language server for C/C++ like CQuery to get symbol information to use them in an UML model. Establishing a connection to CQuery, send a request runs pretty well. Now I have problems understanding how to receive a list of symbol information (SymbolInformation[]).

So far, I've seen a client example, hover_success, how to request the hover information.

How does it work for requests which return a  list like 'workspace/symbol' of 'SymbolInformation[]'. The <TResponse> should then be a list.

From looking at the code I can imagine that it has something to do with 'SymbolInformationContainer'.  Is there an example, suggestions, or some help available?

Thanks for your help,

Helmut

**Comment by tintoy** [comment]
Hi - `XXXContainer` types are generally `IEnumerable<XXX>`, so you can do one of 2 things to examine their contents: iterate or convert to list / array.

```csharp
SymbolInformationContainer symbolContainer;
foreach (SymbolInformation symbol in symbolContainer)
{
  // Use symbol information.
}
```

Or more conveniently:

```csharp
using System.Linq;

SymbolInformationContainer symbolContainer;

SymbolInformation[] symbols = symbolContainer.ToArray();
```

**Comment by tintoy** [comment]
The client doesn't currently expose a typed wrapper for `workspace/symbol`, BTW (I'll look into adding one), but you can easily call it directly like so:

```csharp
SymbolInformationContainer symbols = Client.SendRequest<SymbolInformationContainer>(
  new WorkspaceSymbolParams { Query = "MySymbol" }
);
```

**Comment by Helmut-Ortmann** [comment]
Hi tintoy,

it looks that the json stuff doesn't work with Container.

The beneath test case shows:

-  ok: JObject.FromObject(x); (Type: SymbolInformation)
- error: JObject.FromObject(symbolInformationContainer); (Type: SymbolInformationContainer)

 ```
 [Fact(DisplayName = "Simple test")]
        public async Task SimpleTest()
        {
            string expectedContainerName = "1111";
            var symbolInformation = new SymbolInformation[] {
                new SymbolInformation {
                    Name = "Amm_ProcChanged",
                    Location = new Location() {
                        Range = new Range(new Position(1, 2), new Position(3, 4)),
                        Uri = new Uri("file:///abc/123.cs")
                    },
                    ContainerName = expectedContainerName
                },

                new SymbolInformation {
                    Name = "Amm_ProcChanged",
                    Location = new Location() {
                        Range = new Range(new Position(5, 6), new Position(7, 8)),
                        Uri = new Uri("file:///abc/123.cs")
                    },
                    ContainerName = expectedContainerName
                }};
            var x = new SymbolInformation {
                Name = "Amm_ProcChanged",
                Location = new Location() {
                    Range = new Range(new Position(5, 6), new Position(7, 8)),
                    Uri = new Uri("file:///abc/123.cs")
                },
                ContainerName = expectedContainerName
            };
                

            var symbolInformationContainer = new SymbolInformationContainer(symbolInformation);
            var test = JObject.FromObject(x); // works
            // var test = JObject.FromObject(symbolInformationContainer); // doesn't work
            var a = test;
        }
```

If the handler throws an exception, the client doesn't receive a response. If using an await an exception is thrown and propagated.

```
#pragma warning disable CS4014 // Continuation does the work we need; no need to await it as this would tie up the dispatch loop.
           await handlerTask.ContinueWith(_ =>
            {
                if (handlerTask.IsCanceled)
```

Best regards,

Helmut

**Comment by tintoy** [comment]
Oops! Sorry, yes, that's a bug :-)

Should be using `JToken.FromObject` not `JObject.FromObject` I think. I'll have a go at fixing that shortly.

**Comment by tintoy** [comment]
Would you mind trying out the change I made in [667864d061376073ad61d319def33f8fedecfccb](https://github.com/tintoy/csharp-language-server-protocol/commit/667864d061376073ad61d319def33f8fedecfccb) to see if that improves matters for you?

**Comment by Helmut-Ortmann** [comment]
Ye, I'll tell you the result, thanks for your help! I

**Comment by tintoy** [comment]
Hi @Helmut-Ortmann, have you had a chance to see whether this fixes your problem (FWIW it looks to me like it has but I'll wait for confirmation)?

**Comment by Helmut-Ortmann** [comment]
Hi Adam,

as I wrote you on 6. January:

you should consider also changing the type of Result in *ServerMessage* to
JToken. The code:

LspConnection,757:
ServerMessage message =
JsonConvert.DeserializeObject<ServerMessage>(responseBody);

throws an exception which results in not proper control flow.

After changing the type to JToken everything runs smooth for Symbols.

Maybe also consider wrapping JSON with Try Catch.

Thanks for your great help,

Helmut

**Comment by tintoy** [comment]
Oops don't know how I missed that! Thanks.
