### ISSUE TITLE
Do the threads returned by a ThreadsHandler need to be real threads?

### ISSUE THREAD

**Issue by rjmholt** [OmniSharp/csharp-language-server-protocol#566]
Today, a `ThreadsHandler` returns a `Container<System.Threading.Thread>` and debugger events send through the ID of the affected thread.

In a world where most of our backend is async we don't really have a specific thread for anything we're debugging (in PowerShell we technically do, but it's kind of hard to get to).

So if we want to send back a thread through the ThreadsHandler, the easiest thing to do is to create a dummy thread object to represent the debugged thread -- but if that's the case, we might be better off with an O#-defined object to represent a thread.

Today we send back an empty container and always set `AllThreadsStopped` and `AllThreadsContinued`, but that might not be a good way to go...?

**Comment by rjmholt** [comment]
In particular I notice there's a type called `Omnisharp.Extensions.DebugAdapter.Protocol.Models.Thread` that seems appropriate for this

**Comment by yevgeni-zolotko** [comment]
I also noticed the same issue. I think this is a bug in a code generator which confuses `Omnisharp.Extensions.DebugAdapter.Protocol.Models.Thread` with `System.Threading.Thread`.
This leads to a JSON serialization exception, so using the `threads` request crashes the application.
