### ISSUE TITLE
Potential race condition with initialized handler

### ISSUE THREAD

**Issue by andschwa** [OmniSharp/csharp-language-server-protocol#588]
So @rjmholt and I have been debugging an issue with the PowerShell extension after updating to v3.19, and we believe have tracked it down to a race condition. But we don't know if this is an issue with OmniSharp, or maybe even with the LSP spec itself.

We see that the `Initialize` request handler, for LSP2, sets `Initialized`:

https://github.com/OmniSharp/csharp-language-server-protocol/blob/005c87f1c41da3f1b2b35f32c98e3d3132df99a3/src/Server/LanguageServer.cs#L316-L322

This made sense, because `Initialize` was a _request_ and so the client can (and does) wait to hear from the server that `Initialize` was handled. When OmniSharp calls that `initialized()` method (for LSP2) then `GetRequests()` starts behaving "correctly" (handling all notifications and requests):

https://github.com/OmniSharp/csharp-language-server-protocol/blob/1b6788df2600083c28811913a221ccac7b1d72c9/src/Server/LspServerReceiver.cs#L20-L54

But then this was changed for LSP3, we have an `Initialized` (note the D) handler for the `Initialized` _notification_ (which the client cannot wait on). This is problematic because the client then sends more notifications which race the server's handler for the `Initialized` notification, and this race ends up in the requests not being handled, as evidenced by the responses "Unexpected request" and "Unexpected notification" in `GetRequests`.

https://github.com/OmniSharp/csharp-language-server-protocol/blob/005c87f1c41da3f1b2b35f32c98e3d3132df99a3/src/Server/LanguageServer.cs#L327-L337

This correlates with the logs we have when we see a bug in the PowerShell extension:

```
2021-05-06 11:41:07.210 -07:00 [DBG] Finding descriptors for initialize
2021-05-06 11:41:07.382 -07:00 [DBG] Queueing "Serial":initialize:0 request for processing
2021-05-06 11:41:07.428 -07:00 [DBG] Starting: Processing request initialize 0
2021-05-06 11:41:07.444 -07:00 [DBG] Starting: Routing Request (0) initialize
2021-05-06 11:41:08.131 -07:00 [DBG] Finished: Routing Request (0) initialize in 687ms
2021-05-06 11:41:08.131 -07:00 [DBG] Finished: Processing request initialize 0 in 702ms
2021-05-06 11:41:08.211 -07:00 [DBG] Finding descriptors for initialized
2021-05-06 11:41:08.211 -07:00 [DBG] Queueing "Serial":initialized request for processing
2021-05-06 11:41:08.232 -07:00 [WRN] Unexpected notification workspace/didChangeConfiguration {"Method":"workspace/didChangeConfiguration","Params":[[[[[[[[[]],[[]]]],[[]],[[]],[[]],[[]],[[]],[[[[]],[[]]]],[[]],[[]],[[]],[[[[]]]],[[]],[[]],[[[[]],[[]]]],[[[[]],[[]]]],[[[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]]]],[[[[]],[[]],[[]],[[]],[[]]]],[[[[]]]],[[[[]],[[]],[[]],[[]],[[]]]],[[[[]],[[]],[[]]]],[[[[]],[[]]]]]],[[[[[[]]]],[[[[]],[[]],[[]],[[]],[[]]]],[[[[]],[[]]]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[[[]],[[]],[[]],[[]]]],[[]],[[]],[[]],[[]],[[]],[[[[]]]]]],[[[[[[]],[[]],[[]]]],[[]],[[]],[[]],[[]],[[]],[[[[]],[[]],[[null]]]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[[[]],[[]],[[]]]],[[]]]]]]],"TraceParent":null,"TraceState":null,"$type":"Notification"}
2021-05-06 11:41:08.233 -07:00 [WRN] Unexpected request powerShell/getVersion {"Id":1,"Method":"powerShell/getVersion","Params":null,"TraceParent":null,"TraceState":null,"$type":"Request"}
2021-05-06 11:41:08.234 -07:00 [WRN] Tried to send request or notification before initialization was completed and will be sent later {"Id":null,"Error":{"Code":-32002,"Data":null,"Message":"Server Not Initialized","$type":"ErrorMessage"},"Method":"powerShell/getVersion","$type":"ServerNotInitialized"}
2021-05-06 11:41:08.234 -07:00 [DBG] Starting: Processing notification initialized
2021-05-06 11:41:08.243 -07:00 [DBG] Starting: Routing Notification initialized
2021-05-06 11:41:08.366 -07:00 [DBG] Finished: Routing Notification initialized in 132ms
2021-05-06 11:41:08.366 -07:00 [DBG] Finished: Processing notification initialized in 141ms
```

We think this may be related to #556, @david-driscoll was there any update on your investigation into that issue? @majastrz does any of this make sense to you and sound related to your issue?

**Comment by majastrz** [comment]
It could certainly explain my issue. I think I can add logging for the "Unexpected request" events in my repro. If I see that logged for legitimate LSP requests/notifications, it would confirm the hypothesis.

**Comment by david-driscoll** [comment]
So the naming is wrong (more specifically it was never changed).  `_initializeComplete` == both the server and client are ready

What is happening is that in lsp v2, the server and client was assumed to be ready for everything immediately after the `initialize` request was finished.  With v3 the server must wait for `initialized` to be sent before responding to other requests.
Based on this language [here](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialized).

As I'm typing this, it's entirely possible that I'm reading or understanding it wrong, and simply moving the `_serverReceiver.Initialized();` to always happen at the end of `initialize` maybe the correct thing to do.

**Comment by david-driscoll** [comment]
In addition there are two phases where you can add hooks.  

Today there are three different hooks in the setup process (perhaps confusingly)

* `IOnLanguageServerInitialize` and `OnLanguageServerInitializeDelegate` -- This allows you to manipulate client capabilities before they're read by the server
* `IOnLanguageServerInitialize` and `OnLanguageServerInitializedDelegate` -- This allows you to manipulate the server capabilities before they're sent back to the client.
* `IOnLanguageServerStarted` and `OnLanguageServerStartedDelegate` -- This is right after the `initialized` event is received.

If you have any logic in `IOnLanguageServerInitialize` or `IOnLanguageServerInitialize` that requires calls to the client, if you move it to `IOnLanguageServerStarted` things might start behaving better.

**Comment by rjmholt** [comment]
We initially were looking into our server -> client calls, but I think our issue is actually coming from a client call to the server.

Another example of a request we were seeing fail here was when we send a custom request at startup to query the PowerShell version being used, [here](https://github.com/PowerShell/vscode-powershell/blob/6ab8ecce949385f1854195bcdae54ad5063d1520/src/session.ts#L566). We were worried that this `onReady()` callback was the wrong place and that it was too early, so dove into the VSCode implementation to find out.

It turns out that [`onReady()` is indeed only called after the `initialize` response is received and the `initialized` notification is sent](https://github.com/microsoft/vscode-languageserver-node/blob/2645fb54ea1e764aff71dee0ecc8aceff3aabf56/client/src/common/client.ts#L3247-L3289), **but** the client can't wait for the notification to be received by the server (that doesn't make sense since it's a notification). So it can immediately also send another request or notification.

Essentially, we think there's some period of time in O# after the `initialize` response is sent but before the `initialized` notification is processed when the client is free to send messages to O# according to LSP, but O# will reject them. While O# is still processing the `initialized` notification, the client has already sent and O# has already received another notification and rejected it, even though O# has sent an `initialize` response permitting that behaviour from the client.

**Comment by andschwa** [comment]
> As I'm typing this, it's entirely possible that I'm reading or understanding it wrong, and simply moving the `_serverReceiver.Initialized();` to always happen at the end of `initialize` maybe the correct thing to do.

I _think_ this is the right move. The spec is a bit hard to understand, but first there's the [`Initialize` request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize):

> The initialize request is sent as the first request from the client to the server. If the server receives a request or notification before the initialize request it should error.

This is fine, our client (which just uses `vscode-languageclient`) doesn't send other requests at this point (we have some requests being sent by our server implementation, like to itself, and that confused us for a while, but they're being appropriately handled and aren't the cause of the bug).

Secondly, there's the [`Initialized` notification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialized):

> The initialized notification is sent from the client to the server _after_ the client received the result of the initialize request but _before_ the client is sending any other request or notification to the server.

Ok, great, but this is annoying! Our client has sent `initialized`, a notification that it cannot wait on (in contrast to a request) and then is totally allowed to send any other request or notification, which it starts doing. But these subsequent requests and notifications are _erroneously_ handled by `LspServerReceiver.GetRequest()` because of the race condition around `_initialized`, which is set in the server's handler for the `Initialized` request, and hence may still be `false` when the next notifications come in.

https://github.com/OmniSharp/csharp-language-server-protocol/blob/1b6788df2600083c28811913a221ccac7b1d72c9/src/Server/LspServerReceiver.cs#L22

In our case, we're depending on "Unexpected notification workspace/didChangeConfiguration" and "Unexpected request powerShell/getVersion" to actually be processed correctly, as they are _not_ supposed to be unexpected since they were sent by the client after it sent its initialized notification.

**Comment by majastrz** [comment]
Can't wait to try this out! ❤

**Comment by majastrz** [comment]
`v0.19.2-beta0002` worked perfectly with Bicep!

**Comment by andschwa** [comment]
Yay!!! Awesome to hear @majastrz.
