### ISSUE TITLE
Request symbol/query for empty string throws exception

### ISSUE THREAD

**Issue by Helmut-Ortmann** [OmniSharp/csharp-language-server-protocol#64]
An empty string as a symbol makes in my opinion sense. I would like to use it to get all available symbols to store them in an SQL database.

Language server like CQuery are supporting empty query requests (all symbols) and are returning all or max amount of symbols according to the configuration.

Best regards,

Helmut

**Comment by david-driscoll** [comment]
@Helmut-Ortmann is there anything that is explicitly throwing on our end?

The comment in question just comes from https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#workspace-symbols-request-leftwards_arrow_with_hook .  I don't think we actually validate that in any way.

**Comment by Helmut-Ortmann** [comment]
Hi David,

thanks for your quick and correct response.

Sorry, if I'm right I've inserted the function. So I have to blame myself.

Best regards,

Helmut
