### ISSUE TITLE
Support for setting minimum log level

### ISSUE THREAD

**Issue by tintoy** [OmniSharp/csharp-language-server-protocol#69]
Currently, the built-in logger ([LanguageServerLogger](https://github.com/OmniSharp/csharp-language-server-protocol/blob/023ac405f7350760f161e3fe8b26434d0c0894d1/src/Server/LanguageServerLogger.cs)) for `LanguageServer` has no way to set a minimum logging level, and so all (even diagnostic-level) messages are unconditionally forwarded to the LSP client via `window/logMessage`.

Ideally, there would be a way to control the log level. Perhaps via a mutable property on `LanguageServer`?

CC: @david-driscoll

**Comment by david-driscoll** [comment]
Makes sense to me.

**Comment by tintoy** [comment]
Ok will work up a PR :)

**Comment by tintoy** [comment]
Thanks!
