### ISSUE TITLE
We need logging for ProcessScheduler

### ISSUE THREAD

**Issue by tintoy** [OmniSharp/csharp-language-server-protocol#77]
I've run into weird behaviour (tintoy/msbuild-project-tools-vscode#36) where my language server shuts down, but the process fails to terminate (but only on Linux) because it's blocked [here](https://github.com/OmniSharp/csharp-language-server-protocol/blob/80e1b387ad7ad6d8df7ce944646cb04e07391ea4/src/JsonRpc/ProcessScheduler.cs#L126).

The scheduler's process is a little opaque right now, so if nobody minds I'd like to add some useful telemetry in the form of logging so I can see what's going on.

Any objections, @david-driscoll?

**Comment by david-driscoll** [comment]
Got nuts, the more logging the better imo.
