### ISSUE TITLE
[LSP] Language server returns improper URIs

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/csharp-language-server-protocol#79]
See https://github.com/OmniSharp/omnisharp-roslyn/issues/1125

**Comment by tintoy** [comment]
I ran into this a while back; here's how I dealt with it :grin:

https://github.com/tintoy/msbuild-project-tools-server/blob/master/src/LanguageServer.Common/Utilities/VSCodeDocumentUri.cshttps://github.com/tintoy/msbuild-project-tools-server/blob/master/src/LanguageServer.Common/Utilities/VSCodeDocumentUri.cs
