### ISSUE TITLE
Confused about handlers and registrations

### ISSUE THREAD

**Issue by kalbj** [OmniSharp/csharp-language-server-protocol#80]
I'm trying to implement a prototype `IWorkspaceSymbolsHandler` in the sample server.
This interface implements `IRequestHandler` and `ICapability`, but unlike some of the other handlers, it doesn't implement `IRegistration`.

When `LanguageServer.DynamicallyRegisterHandlers` runs, it ends up attempting to call `RegisterCapability` with a null registration for this handler, which causes an exception and the server to disconnect and shutdown.

Clearly i'm doing something wrong - any advice appreciated.

The `HandlerDescriptor` has `AllowsDynamicRegistration=true` and `HasRegistration=false`

Should `DynamicallyRegisterHandlers` also be checking for `HasRegistration` to protect against this?
https://github.com/OmniSharp/csharp-language-server-protocol/blob/fae86e0112914c43d279385114260792efd613b2/src/Server/LanguageServer.cs#L305-L308

**Comment by tgjones** [comment]
I'm getting the same crash, when implementing either `IWorkspaceSymbolsHandler ` or `IDocumentSymbolHandler`.

**Comment by tintoy** [comment]
I think this stuff was recently changed, is that right @david-driscoll?

**Comment by david-driscoll** [comment]
@kalbj sorry I didn't see this earlier.

I believe you are correct, other similar calls all have a null check, but `HasRegistration` makes more sense.  
Will be updating.
