### ISSUE TITLE
Completion handler cannot get completion context sent by client

### ISSUE THREAD

**Issue by ghost** [OmniSharp/csharp-language-server-protocol#83]
I'm working on a language server and using Vscode as client. Vscode client supports completion context, but ICompletionHandler provides only a TextDocumentPositionParams parameter. When I try to cast it to a CompletionParams, I get an InvalidCastException. Is there no way I can extract the completion context ?

**Comment by david-driscoll** [comment]
That's definitely a bug, I'll fix that with the next push.
