### ISSUE TITLE
Should send jsonrpc instead of protocolVersion in messages

### ISSUE THREAD

**Issue by Daniel-V1** [OmniSharp/csharp-language-server-protocol#98]
Hello,

I finally figured out why this wasn't working with lsp-mode, and it has to do with the fact that lsp-mode is looking specifically for the jsonrpc key in the message, which this seems to instead call protocolVersion. In looking at the spec, it seems that jsonrpc is the correct key, at least it is what's shown in the examples. Please let me know if I am missing something.

Thanks!

**Comment by david-driscoll** [comment]
@Daniel-V1 omg!  thanks for that... that's a huge miss on my part... jeeeeezzzzzz.
