### ISSUE TITLE
InputHandler doesn’t work with non-blocking streams

### ISSUE THREAD

**Issue by mholo65** [OmniSharp/csharp-language-server-protocol#99]
If using a `MemoryStream` as `Input`, the `InputHandler` threaf will return immedeatly when there’s nothing to read from the stream. https://github.com/OmniSharp/csharp-language-server-protocol/blob/master/src/JsonRpc/InputHandler.cs#L78

When reading from e.g. STDIN, the read method will block until there’s something to read, therefore it works there :smile:

**Comment by tintoy** [comment]
Have a look at the tests for the LSP client - I use NamedPipeStreams for this reason :)

PS. Anonymous pipes don't support async!

**Comment by tintoy** [comment]
It's a pity Stream never declared an Is locking or CanBlock property :-/

**Comment by david-driscoll** [comment]
we can probably safely change this to just wait around and try again later to see if there is anything on the stream to read.

**Comment by mholo65** [comment]
@tintoy yes, read loop will become a little more complex. But for now, I can work around this by implementing my own blocking memory stream.

On a side note.: It's really, really stupid in .NET that some streams block on reading, while some return immediately. Hell, `MemoryStream` even throws if one tries to set `ReadTimeout`...

**Comment by tintoy** [comment]
@mholo65 - was going to maybe suggest `System.IO.Pipelines` being a way to abstract read loop from stream type? Perhaps I could look into that for the client (since that's used by fewer people) and if it works we could use it for the server implementation as well?

**Comment by david-driscoll** [comment]
I think this has been achieved at this point, @mholo65 please re-open if you don't think so.
